/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gladoctorGui;

import gladoctor.SystemController;
import gladoctor.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ste
 */
public class addUser extends javax.swing.JPanel {

    /**
     * Creates new form addUser
     */
    public addUser() {
        initComponents();
    }

    public void init(){
        newFisCod.setDocument (new JTextFieldLimit(16));
        errLabel4.setVisible(false);
        sLab.setVisible(false);
    }
    public void doResetAddUser(){
        
    }
    public void doAddUser(){
        if( (newName.getText().length() > 0 && newSurname.getText().length() > 0 && newFisCod.getText().length() > 0 &&
           newUserName.getText().length() > 0 && newPwd.getText().length() > 0 && confNewPwd.getText().length() > 0) && (confNewPwd.getText().equals(newPwd.getText()) ) ){ //TODO eventualmente piccolo avviso nel caso le password divergono
            User temp = SystemController.currentUser.createUser();
            temp.setName(newName.getText());
            temp.setSurname(newSurname.getText());
            temp.setFiscalCode(newFisCod.getText());
            temp.setUsername(newUserName.getText());
            temp.setPassword(GuiController.SHA1(newPwd.getText().getBytes()));
            temp.setAdmin(false);
            temp.setSubstituteOf("0");
            temp.sendData();
            sLab.setVisible(true);
                        try {
                Thread.sleep(500);
                        } catch (InterruptedException ex) {
                        Logger.getLogger(addUser.class.getName()).log(Level.SEVERE, null, ex);
                        }
            sLab.setVisible(false);
            //TODO repaint dell lista utenti e metti un indietro
            GuiController.showMainPanel();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        newName = new javax.swing.JTextField();
        newSurname = new javax.swing.JTextField();
        newFisCod = new javax.swing.JTextField();
        newUserName = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        errLabel4 = new javax.swing.JLabel();
        sLab = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        newPwd = new javax.swing.JPasswordField();
        confNewPwd = new javax.swing.JPasswordField();

        jLabel1.setText("Nome:");

        jLabel2.setText("Cognome:");

        jLabel3.setText("Cod. fiscale:");

        jLabel4.setText("Username:");

        jLabel5.setText("Password:");

        jLabel6.setText("Conferma password:");

        jButton1.setText("Conferma");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addUser(evt);
            }
        });

        jButton2.setText("Reset");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetAddUser(evt);
            }
        });

        errLabel4.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        errLabel4.setForeground(new java.awt.Color(255, 3, 0));
        errLabel4.setText("ERRORE");
        errLabel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 2, true));

        sLab.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        sLab.setForeground(new java.awt.Color(12, 187, 8));
        sLab.setText("    OK    ");
        sLab.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 206, 12), 2, true));

        jLabel7.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel7.setText("Inserisci i dati:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(confNewPwd, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(newPwd)
                            .addComponent(newUserName)
                            .addComponent(newFisCod)
                            .addComponent(newName)
                            .addComponent(newSurname)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(errLabel4)
                        .addGap(37, 37, 37)
                        .addComponent(sLab)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(newName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(newSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(newFisCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(newUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(newPwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(confNewPwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(sLab)
                    .addComponent(errLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addUser(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addUser
        doAddUser();
    }//GEN-LAST:event_addUser

    private void resetAddUser(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetAddUser
        doResetAddUser();
    }//GEN-LAST:event_resetAddUser

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField confNewPwd;
    private javax.swing.JLabel errLabel4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField newFisCod;
    private javax.swing.JTextField newName;
    private javax.swing.JPasswordField newPwd;
    private javax.swing.JTextField newSurname;
    private javax.swing.JTextField newUserName;
    private javax.swing.JLabel sLab;
    // End of variables declaration//GEN-END:variables
}
