/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gladoctorGui;
import gladoctor.*;
import java.util.*;
import javax.swing.table.*;
import java.awt.event.KeyEvent;
import java.io.File;
/**
 *
 * @author ste
 */
public class MainPanel extends javax.swing.JPanel {

	private static final long serialVersionUID = 1L;
	/**
     * Creates new form MainPanel
     */
    public MainPanel() {
        initComponents();
        //On visibility, set current user name
    }
    
    public void init(){
        currUser.setText(SystemController.currentUser.getName());
        fisCodeAdd.setDocument (new JTextFieldLimit(16));
        bDay.setDocument (new JTextFieldLimit(2));
        bMonth.setDocument (new JTextFieldLimit(2));
        bYear.setDocument (new JTextFieldLimit(4));
        invPerc.setDocument (new JTextFieldLimit(3));
        errLabel7.setVisible(false);
        errLabel4.setVisible(false);
        errLabel5.setVisible(false);
        if( SystemController.currentUser.getSubstituteOf().equals("0") ){
            currSubst.setText("Nessuno");
        }else{
            currSubst.setText(SystemController.currentUser.getSubstNameSurname( SystemController.currentUser.getSubstituteOf()) );
        }
        doResetMP();
        if(SystemController.currentUser.isAdmin()){
            doChooseSubst.setVisible(false);    //Admin non può scegliere sostituti.
            doRmSubst.setVisible(false);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */  
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        surname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        doSearch = new javax.swing.JButton();
        doResetSearch = new javax.swing.JButton();
        doOpenMR = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        errLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        searchRes = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        nameAdd = new javax.swing.JTextField();
        surAdd = new javax.swing.JTextField();
        addrAdd = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        placeBornAdd = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        fisCodeAdd = new javax.swing.JTextField();
        doAddPaziente = new javax.swing.JButton();
        doResetAddForm = new javax.swing.JButton();
        bDay = new javax.swing.JTextField();
        errLabel4 = new javax.swing.JLabel();
        bYear = new javax.swing.JTextField();
        bMonth = new javax.swing.JTextField();
        areaCode = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        exemptCode = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cityLiving = new javax.swing.JTextField();
        occupation = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        tel = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        invPerc = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        currPwd = new javax.swing.JPasswordField();
        newPwd = new javax.swing.JPasswordField();
        confPwd = new javax.swing.JPasswordField();
        doChangePwd = new javax.swing.JButton();
        doResetFields = new javax.swing.JButton();
        doChooseSubst = new javax.swing.JButton();
        doRmSubst = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        currSubst = new javax.swing.JLabel();
        doDelUser = new javax.swing.JButton();
        doAddUser = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        substList = new javax.swing.JTable();
        errLabel7 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        currUser = new javax.swing.JLabel();
        doLogout = new javax.swing.JButton();

        surname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                search2(evt);
            }
        });

        jLabel3.setText("Cognome:");

        doSearch.setText("Cerca");
        doSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchMR(evt);
            }
        });
        doSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchEnt(evt);
            }
        });

        doResetSearch.setText("Reset");
        doResetSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetMPSearch(evt);
            }
        });

        doOpenMR.setText("Apri scheda selezionata");
        doOpenMR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OpenMR(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel2.setText("Risultati:");

        errLabel5.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        errLabel5.setForeground(new java.awt.Color(255, 3, 0));
        errLabel5.setText("ERRORE");
        errLabel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 2, true));

        searchRes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod. fiscale", "Nome, cognome"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        searchRes.setColumnSelectionAllowed(true);
        searchRes.getTableHeader().setReorderingAllowed(false);
        searchRes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchResMouseClicked(evt);
            }
        });
        searchRes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                openMR2(evt);
            }
        });
        jScrollPane2.setViewportView(searchRes);
        searchRes.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        searchRes.setCellSelectionEnabled(false);
        searchRes.setRowSelectionAllowed(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 744, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(doOpenMR, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(errLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(doSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(doResetSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(surname)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(surname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(doResetSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(doSearch))
                .addGap(123, 123, 123)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(errLabel5)
                    .addComponent(doOpenMR))
                .addContainerGap())
        );

        surname.requestFocusInWindow();

        jTabbedPane1.addTab("Ricerca paziente", jPanel1);

        jLabel9.setText("Nome:");

        jLabel10.setText("Cognome:");

        jLabel11.setText("Indirizzo:");

        jLabel12.setText("Data di nascita:");

        jLabel13.setText("Luogo di nascita:");

        jLabel14.setText("Codice fiscale:");

        doAddPaziente.setText("Aggiungi paziente");
        doAddPaziente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addPat(evt);
            }
        });

        doResetAddForm.setText("Reset");
        doResetAddForm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetAdd(evt);
            }
        });

        errLabel4.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        errLabel4.setForeground(new java.awt.Color(255, 3, 0));
        errLabel4.setText("ERRORE");
        errLabel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 2, true));

        jLabel6.setText("CAP:");

        jLabel7.setText("Codice Esenzione:");

        jLabel8.setText("Citta' di residenza:");

        jLabel15.setText("Occupazione:");

        jLabel16.setText("Tel.");

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel20.setText("% invalidita':");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel14)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(fisCodeAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(placeBornAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel11)
                                        .addComponent(jLabel12))
                                    .addGap(34, 34, 34)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(bDay, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(bMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(bYear, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(addrAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(surAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(nameAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cityLiving, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(24, 24, 24)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(106, 106, 106)
                                .addComponent(areaCode, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(exemptCode, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16))
                                .addGap(43, 43, 43)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tel, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(occupation, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addGap(54, 54, 54)
                                .addComponent(invPerc, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 5, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(doAddPaziente)
                        .addGap(18, 18, 18)
                        .addComponent(doResetAddForm, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(errLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(nameAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(areaCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(surAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(addrAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(exemptCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(occupation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel20)
                                    .addComponent(invPerc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(bDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(cityLiving, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(placeBornAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(fisCodeAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doAddPaziente)
                    .addComponent(doResetAddForm)
                    .addComponent(errLabel4))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Aggiunta paziente", jPanel2);

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel5.setText("Cambio password:");

        jLabel17.setText("Password attuale:");

        jLabel18.setText("Nuova password:");

        jLabel19.setText("Conferma:");

        confPwd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                changePwd2(evt);
            }
        });

        doChangePwd.setText("Cambia");
        doChangePwd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changePwd(evt);
            }
        });

        doResetFields.setText("Reset");
        doResetFields.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetPwdChg(evt);
            }
        });

        doChooseSubst.setText("Scegli sost.");
        doChooseSubst.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chooseSubst(evt);
            }
        });

        doRmSubst.setText("Rimuovi sost.");
        doRmSubst.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removeSubst(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel22.setText("Stai sostituendo:");

        currSubst.setForeground(new java.awt.Color(7, 197, 25));
        currSubst.setText("Nessuno");

        doDelUser.setText("-");
        doDelUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rmUser(evt);
            }
        });

        doAddUser.setText("+");
        doAddUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addUser(evt);
            }
        });

        substList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Cod. fiscale"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        substList.setColumnSelectionAllowed(true);
        substList.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(substList);
        substList.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        substList.setCellSelectionEnabled(false);
        substList.setRowSelectionAllowed(true);

        errLabel7.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        errLabel7.setForeground(new java.awt.Color(255, 3, 0));
        errLabel7.setText("ERRORE");
        errLabel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 2, true));

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel4.setText("Scegli il tuo sostituto:");

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(currPwd))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(18, 18, 18)
                                .addComponent(newPwd, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(63, 63, 63)
                                .addComponent(confPwd))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(doChangePwd, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(doResetFields)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(doChooseSubst)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 183, Short.MAX_VALUE)
                                        .addComponent(doRmSubst))
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(doAddUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(doDelUser, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel22)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(currSubst))
                                    .addComponent(jLabel4))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jSeparator2)))
                    .addComponent(errLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator4)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel22)
                                .addComponent(currSubst)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(doChooseSubst)
                                            .addComponent(doRmSubst))
                                        .addGap(6, 6, 6))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(doAddUser)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(doDelUser)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17)
                                    .addComponent(currPwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel18)
                                    .addComponent(newPwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel19)
                                    .addComponent(confPwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(doChangePwd)
                                    .addComponent(doResetFields))
                                .addGap(0, 240, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errLabel7)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Gestione utente", jPanel3);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel1.setText("Welcome to GlaDoctor, ");

        currUser.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        currUser.setText("NOMEMEDICO");

        doLogout.setText("Logout");
        doLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(currUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(doLogout)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(currUser)
                    .addComponent(doLogout))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void loadUserList(){
        DefaultTableModel usrlistmodel = (DefaultTableModel) substList.getModel();
        usrlistmodel.setRowCount(0);
        substList.setModel(usrlistmodel);
        substList.repaint();
        users = SystemController.currentUser.getUserList();
        if(users != null){
            String[] keys = new String[users.size()];
            String[] values = new String[users.size()];
            keys = users.keySet().toArray(keys);
            values = users.values().toArray(values);

            for (int j = 0; j < users.size(); j++){
                String[] data = new String[2];

                data[1] = keys[j];
                data[0] = values[j];
                usrlistmodel.addRow(data);
            }
            substList.setModel(usrlistmodel);
            substList.repaint();
        }else GuiController.taskFail(errLabel7);
    }
    public void doSearch(){ //Avvia ricerca con tutti i campi 
        doSearch.setVisible(false);
        Map<String,String> temp;
        DefaultTableModel tableModel = (DefaultTableModel) searchRes.getModel();
        DefaultTableModel tableModel2 = (DefaultTableModel) searchRes.getModel();
            tableModel2.setRowCount(0);
            searchRes.setModel(tableModel2);
            searchRes.repaint();
            
        temp = SystemController.currentUser.searchMR(surname.getText());
        if(temp != null){
            String[] keys = new String[temp.size()];
            String[] values = new String[temp.size()];
            keys = temp.keySet().toArray(keys);
            values = temp.values().toArray(values);

            for (int j = 0; j < temp.size(); j++) {
                String[] data = new String[2];

                data[0] = keys[j];
                data[1] = values[j];
                tableModel.addRow(data);
            }
            searchRes.setModel(tableModel);
            searchRes.repaint();
            doSearch.setVisible(true);
        }
        doSearch.setVisible(true);
    }
    public void giveInputFocus(){
        surname.requestFocusInWindow();
    }
    public void doOpenMR(){ //Apri MedicalRecord *DEL PAZIENTE SELEZIONATO NELLA TABELLA*
        if(searchRes.getSelectedRow() != -1){
            patientFisCod = (String) searchRes.getValueAt(searchRes.getSelectedRow(), 0);
            medrec = new MedicalRecord(patientFisCod);
            GuiController.showMRPanel();
        }
    }
    
    public void doAddPat(){ //Aggiungi nuovo paziente
        MedicalRecord temp;
        temp = SystemController.currentUser.createMR();
        
        if (nameAdd.getText().length() > 0 && surAdd.getText().length() > 0 && addrAdd.getText().length() > 0 &&
                placeBornAdd.getText().length() > 0 && fisCodeAdd.getText().length() == 16 && bDay.getText().length() > 0 &&
                bMonth.getText().length() > 0 && bYear.getText().length() > 0 && cityLiving.getText().length() > 0 &&
                areaCode.getText().length() == 5 && ((exemptCode.getText().length() % 3) == 0 || exemptCode.getText().equals("N")) &&
                occupation.getText().length() > 0 && tel.getText().length() > 0){
            temp.setFiscalCode(fisCodeAdd.getText());
            temp.getDataSheet().setName(nameAdd.getText());
            temp.getDataSheet().setSurname(surAdd.getText());
            temp.getDataSheet().setFiscalCode(fisCodeAdd.getText());
            temp.getDataSheet().setAddress(addrAdd.getText());
            temp.getDataSheet().setAreaCode(areaCode.getText());
            temp.getDataSheet().setCityLiving(cityLiving.getText());
            temp.getDataSheet().setPlaceBorn(placeBornAdd.getText());
            temp.getDataSheet().setDateBorn(bYear.getText()+"-"+bMonth.getText()+"-"+bDay.getText());
            temp.getDataSheet().setOccupation(occupation.getText());
            temp.getDataSheet().setTelephoneNumber(tel.getText());
            temp.getDataSheet().setExemptionCode(exemptCode.getText());
            temp.getMainBoard().setFiscalCode(fisCodeAdd.getText());
            temp.getMainBoard().setInvalidityPercentage( Integer.parseInt(invPerc.getText()) );

            if(temp.sendData()) { GuiController.taskSuccess(errLabel4); doResetMPaddPat(); }
            else GuiController.taskFail(errLabel4);
        }else GuiController.taskFail(errLabel4);
    }
    
    public void doChangePwd() throws InterruptedException{
        if(currPwd.getText().length() > 0 && newPwd.getText().length() > 0 && confPwd.getText().length() > 0
                && (newPwd.getText().equals(confPwd.getText())) ){
            if( !(SystemController.currentUser.changePwd( GuiController.SHA1(currPwd.getText().getBytes()),
                                                          GuiController.SHA1(newPwd.getText().getBytes())))){
                GuiController.taskFail(errLabel7);
                Thread.sleep(1000);
                errLabel7.setVisible(false);
            }else GuiController.taskSuccess(errLabel7);
        }
        doResetPwdChg();
    }
    
    public void doChooseSubst(){    //Scegli sostituto
        String subst = (String) substList.getValueAt(substList.getSelectedRow(), 1);
        
        if( SystemController.currentUser.enableSubstitute(subst) ){
            GuiController.taskSuccess(errLabel7);
        }else{
            GuiController.taskFail(errLabel7);
                try {
            Thread.sleep(1000);
                 } catch (InterruptedException ex) {
                    System.out.println(ex.getCause().toString());
                 }
            errLabel7.setVisible(false);
        }
    }

    public void doRmSubst(){    //Rimuovi sostituto
        if( SystemController.currentUser.killSubstitute() ){
            GuiController.taskSuccess(errLabel7);
        }else{
            GuiController.taskFail(errLabel7);
                try {
            Thread.sleep(1000);
                 } catch (InterruptedException ex) {
                    System.out.println(ex.getCause().toString());
                 }
            errLabel7.setVisible(false); //TODO repaint dell lista
        }
    }
    public void doAddUser(){
        GuiController.showaddUser();
    }
    
    public void doRmUser(){
        String rmvd = (String) substList.getValueAt(substList.getSelectedRow(), 1);
        if(SystemController.currentUser.deleteUser(rmvd)){
            loadUserList();
            GuiController.taskSuccess(errLabel7);
        }else GuiController.taskFail(errLabel7);
    }
    
    public void doResetMP(){    //resetta tutto il mainpanel
        doResetMPsearch();
        doResetMPaddPat();
        doResetMPUserMgmt();
    }
    public void doResetMPsearch(){  //resetta la tab di ricerca
        surname.setText("");
        DefaultTableModel clean = (DefaultTableModel) searchRes.getModel();
        clean.setRowCount(0);
        searchRes.setModel(clean);  //TODO: sicuro?
        searchRes.repaint();
    }
    public void doResetMPaddPat(){  //resetta la tab di aggiunta paziente
        nameAdd.setText("");
        surAdd.setText("");
        placeBornAdd.setText("");
        addrAdd.setText("");
        bDay.setText("");
        bMonth.setText("");
        bYear.setText("");
        placeBornAdd.setText("");
        fisCodeAdd.setText("");
        cityLiving.setText("");
        areaCode.setText("");
        exemptCode.setText("");
        occupation.setText("");
        tel.setText("");
        invPerc.setText("");
        
    }
    public void doResetPwdChg(){   //resetta la parte di cambio pwd della tab di gestione utente
        currPwd.setText("");
        newPwd.setText("");
        confPwd.setText("");
    }
    public void doResetMPUserMgmt(){    //resetta tutta la tab di gestione utente
        doResetPwdChg();
        loadUserList();
    }
    public void doLogout(){
        GuiController.rmdir(GuiController.getDir());
        GuiController.totalGuiReset();
        GuiController.showLoginPanel();
    }
    public void disableAdminButtons(){
        doAddUser.setVisible(false);
        doDelUser.setVisible(false);
    }

    public void enableAdminButtons(){
        doAddUser.setVisible(true);
        doDelUser.setVisible(true);
    }
    
    private void resetMPSearch(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetMPSearch
        doResetMPsearch();
    }//GEN-LAST:event_resetMPSearch

    private void LogoutClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutClicked
        doLogout();
    }//GEN-LAST:event_LogoutClicked

    private void search2(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search2
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) doSearch();
    }//GEN-LAST:event_search2

    private void resetAdd(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetAdd
        doResetMPaddPat();
    }//GEN-LAST:event_resetAdd

    private void resetPwdChg(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetPwdChg
        doResetPwdChg();
    }//GEN-LAST:event_resetPwdChg

    private void changePwd(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changePwd
        try {
            doChangePwd();
        } catch (InterruptedException ex) {
            System.out.println(ex.getCause().toString());
        }
    }//GEN-LAST:event_changePwd

    private void addPat(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addPat
        doAddPat();
    }//GEN-LAST:event_addPat

    private void chooseSubst(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chooseSubst
        doChooseSubst();
    }//GEN-LAST:event_chooseSubst

    private void removeSubst(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeSubst
        doRmSubst();
    }//GEN-LAST:event_removeSubst

    private void OpenMR(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OpenMR
        doOpenMR();
    }//GEN-LAST:event_OpenMR

    private void searchMR(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMR
        doSearch();
    }//GEN-LAST:event_searchMR

    private void openMR2(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_openMR2
        doOpenMR();
    }//GEN-LAST:event_openMR2

    private void searchResMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchResMouseClicked
        if (evt.getClickCount() == 2){
            doSearch();
        }
    }//GEN-LAST:event_searchResMouseClicked

    private void changePwd2(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_changePwd2
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) try {
            doChangePwd();
        } catch (InterruptedException ex) {
            System.out.println(ex.getCause().toString());
        }
    }//GEN-LAST:event_changePwd2

    private void addUser(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addUser
        doAddUser();
    }//GEN-LAST:event_addUser

    private void rmUser(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rmUser
        doRmUser();
    }//GEN-LAST:event_rmUser

    private void searchEnt(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchEnt
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            doSearch();
    }//GEN-LAST:event_searchEnt
    
    private  Map<String,String> users;
    private String patientFisCod = "";
    public static Examination currEx; 
    public static MedicalRecord medrec;
    public static Prescription prescr;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addrAdd;
    private javax.swing.JTextField areaCode;
    private javax.swing.JTextField bDay;
    private javax.swing.JTextField bMonth;
    private javax.swing.JTextField bYear;
    private javax.swing.JTextField cityLiving;
    private javax.swing.JPasswordField confPwd;
    private javax.swing.JPasswordField currPwd;
    private javax.swing.JLabel currSubst;
    private javax.swing.JLabel currUser;
    private javax.swing.JButton doAddPaziente;
    private javax.swing.JButton doAddUser;
    private javax.swing.JButton doChangePwd;
    private javax.swing.JButton doChooseSubst;
    private javax.swing.JButton doDelUser;
    private javax.swing.JButton doLogout;
    private javax.swing.JButton doOpenMR;
    private javax.swing.JButton doResetAddForm;
    private javax.swing.JButton doResetFields;
    private javax.swing.JButton doResetSearch;
    private javax.swing.JButton doRmSubst;
    private javax.swing.JButton doSearch;
    private javax.swing.JLabel errLabel4;
    private javax.swing.JLabel errLabel5;
    private javax.swing.JLabel errLabel7;
    private javax.swing.JTextField exemptCode;
    private javax.swing.JTextField fisCodeAdd;
    private javax.swing.JTextField invPerc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField nameAdd;
    private javax.swing.JPasswordField newPwd;
    private javax.swing.JTextField occupation;
    private javax.swing.JTextField placeBornAdd;
    private javax.swing.JTable searchRes;
    private javax.swing.JTable substList;
    private javax.swing.JTextField surAdd;
    private javax.swing.JTextField surname;
    private javax.swing.JTextField tel;
    // End of variables declaration//GEN-END:variables
}
